sqlite:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500
postgres:
  adapter: postgresql
  database: quantum_fields_test
  username: postgres
mysql:
  adapter: mysql2
  database: quantum_fields_test
  username: travis
  encoding: utf8
